services:
  app:
    container_name: server-power-ui
    restart: "unless-stopped"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - data:/app/data
    network_mode: "host"

volumes:
  data:
